[build]
  base = "/"
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "21"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
    ]

[[redirects]]
  from = "/docs/community/*"
  to = "/community/:splat"
  status = 301